error creating AsycFileHandler
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 244, in worker
    assert False
AssertionError
error creating AsycFileHandler
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 244, in worker
    assert False
AssertionError
error creating AsycFileHandler
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 244, in worker
    assert False
AssertionError
error creating AsycFileHandler
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 244, in worker
    assert False
AssertionError
error creating AsycFileHandler
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 244, in worker
    assert False
AssertionError
error creating AsycFileHandler
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 244, in worker
    assert False
AssertionError
error creating AsycFileHandler
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 244, in worker
    assert False
AssertionError
error creating AsycFileHandler
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 244, in worker
    assert False
AssertionError
error creating AsycFileHandler
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 244, in worker
    assert False
AssertionError
error creating AsycFileHandler
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 244, in worker
    assert False
AssertionError
error creating AsycFileHandler
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 244, in worker
    assert False
AssertionError
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
An error occured in packet submitter service object dict can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/knowns/workflow/network-monitor-client/network_monitor/services/packet_submitter.py", line 260, in worker
    data: Dict[str, Dict[str, Union[str, int]]] = await service_control.in_queue.get()
TypeError: object dict can't be used in 'await' expression
